package com.elastic.support;

import com.beust.jcommander.*;

public class InputParams {

    @Parameter(names = { "-h", "-?", "--help", "-help" }, help=true)
    private boolean help;

    @Parameter(names = { "-n", "--host", "--name", "--hostname", "-ip" }, description = "Hostname or IP Address used by the cluster and present in the manifest file.  Required. ")
    private String host;

    @Parameter(names = { "-m", "--manifestFile", "--manifest"}, required=true, description = "Manifest file generated by the diagnostics-stats application for this cluster. Be sure to enter with a fully qualified path name. Required")
    String manifestFile;

    @Parameter(names = { "-o", "--out"," --output", "--outputDir" }, description = "Fully qualified path to output directory or c for current working directory.")
    private String outputDir = "cwd";

    @Parameter(names = { "-l", "--logConfig"}, description = "Alternative log configuration file in logback format. Be sure to enter with a fully qualified path name.")
    String logConfig;

    @Parameter(names = { "-c", "--configFile"}, description = "Alternative statements file for diagnostics such as top and netstat. Be sure to enter with a fully qualified path name.")
    String configFile;

    public String getHost() {
        return host;
    }

    public void setHost(String host) {
        this.host = host;
    }

    public String getLogConfig() {
        return logConfig;
    }

    public void setLogConfig(String logConfig) {
        this.logConfig = logConfig;
    }

    public boolean isHelp() {
        return help;
    }

    public void setHelp(boolean help) {
        this.help = help;
    }

    public String getOutputDir() {
        return outputDir;
    }

    public void setOutputDir(String outputDir) {
        this.outputDir = outputDir;
    }

    public String getManifestFile() {
        return manifestFile;
    }

    public void setManifestFile(String manifestFile) {
        this.manifestFile = manifestFile;
    }

    public String getConfigFile() {
        return configFile;
    }

    public void setConfigFile(String configFile) {
        this.configFile = configFile;
    }

    @Override
    public String toString() {
        return "InputParams{" +
                "help=" + help +
                ", host='" + host + '\'' +
                ", outputDir='" + outputDir + '\'' +
                ", logConfig='" + logConfig + '\'' +
                ", manifestFile='" + manifestFile + '\'' +
                ", configFile='" + configFile + '\'' +
                '}';
    }
}
